### PR TITLE
[WFR] on #78

### PR DESCRIPTION
**Pull request by tetsuyam**
I will translate because this section is related to cloud.

### CODE REVIEW

**Comment by tetsuyam** [comment]
I'm sorry for being late to commit. Please review.

**Comment by usk81** [comment]
You foget to change from WIP to WER!!

**Comment by tetsuyam** [comment]
@YusukeKomatsu 
Do you mean WFR??
I'm sorry. I forgot to change the status.

I've changed.
Thank you.

**Comment by ijokarumawak** [comment]
@tetsuyam Thanks for your contribution, I'm reviewing the contents now!

**Comment by ijokarumawak** [comment]
@tetsuyam Review is done, the content is published. Thanks!

**Pull request merged**
