### PR TITLE
Fix ja images

### PR DESCRIPTION
**Pull request by comuttun**
ja/learn/admin/images is symlink, but on not Unix, it cannot be traversable.
So I've copied en/learn/admin/images to ja/learn/admin/images.

### CODE REVIEW

**Comment by ijokarumawak** [comment]
Thanks for your pull request. I didn't pay attention to Windows.

However I didn't want to copy the image files because:
- to minimize file size
- to simplify the way to reflect content change from upstream

I am still considering what is the best way to handle this.

**Comment by comuttun** [comment]
@ijokarumawak 

> - to minimize file size

agreed,

> - to simplify the way to reflect content change from upstream

agreed but I have a question that "ja images are always same as en version" ?
In some cases, ja images will be changed, for example, translate caption from en to ja.

In that cases, shared image architecture will be inconvenience.

If you dislike image duplication, `git submodule` is one of solutions.
And, place 2 image paths, such as `images` and `images-ja`. `images` is for original en images come from upstream with `git submodule`, and `images-ja` is just a directory for replacement.

**Comment by comuttun** [comment]
> And, place 2 image paths, such as images and images-ja. images is for original en images come from upstream with git submodule, and images-ja is just a directory for replacement.

If placing ja version images into upstream is acceptable, 2 image paths are not needed, only 1 image path with `git submodule` is needed.

**Comment by ijokarumawak** [comment]
@comutt Thanks for your suggestion. But I am not going to translate image files for now. Plus I would like to keep it simple as possible.

How about adding ja/*/images to .gitignore, then create a symbolic link if it doesn't exist from rebuild-docs-out.sh (or copying images from en by PowerShell)?

**Comment by comuttun** [comment]
@ijokarumawak :+1:

**Comment by ijokarumawak** [comment]
@comutt I've deleted ja/learn/admin/images and let it gets created when you rebuild the html files.
But I haven't done anything yet for Windows.
Would you modify 'rebuild-docs-out.ps1' to create image dir and copy images int the pull request #446 ?

**Comment by ijokarumawak** [comment]
@commut I have merged #446 to the master, please send a different pull request to handle images dir. Thank you.

**Pull request closed without merging**
